/*
 * TODO_FIRST.h
 *
 *  Created on: Apr 28, 2020
 *      Author: jonathan
 */

#ifndef TODO_FIRST_H_
#define TODO_FIRST_H_


/* IL FAUT TERMINER L'IMPLEMENTATION DU TIMER AVEC TABLEAU,
 * NOTAMMENT L'ANIMATION DE TOMBER DE JETON ! IL EST
 * PREFERABLE DE FINIR D'IMPLEMENTER LE TIMER COMPLETEMENT
 * AVANT DE VOULOIR TESTER LES FONCTIONNALITES CAR IL Y A
 * CERTAINEMENT DES CONFLITS ENTRE LES THREADS.
 */



#endif /* TODO_FIRST_H_ */
